model_list:
  - model_name: "phi4-mini"
    litellm_params:
      model: "ollama_chat/phi4-mini:latest"
      api_base: "http://localhost:11434"
  - model_name: "gpt-4o"
    litellm_params:
      model: "github_copilot/gpt-4o"
      extra_headers:
        "editor-version": "Neovim/0.11.0"
        "Copilot-Integration-Id": "vscode-chat"
  - model_name: "gpt-4.1"
    litellm_params:
      model: "github_copilot/gpt-4.1"
      extra_headers:
        "editor-version": "Neovim/0.11.0"
        "Copilot-Integration-Id": "vscode-chat"
  - model_name: "claude-4-sonnet"
    litellm_params:
      model: "github_copilot/claude-4-sonnet"
      extra_headers:
        "editor-version": "Neovim/0.11.0"
        "Copilot-Integration-Id": "vscode-chat"
  - model_name: "gemini-2.5-pro"
    litellm_params:
      model: "github_copilot/gemini-2.5-pro"
      extra_headers:
        "editor-version": "Neovim/0.11.0"
        "Copilot-Integration-Id": "vscode-chat"
  - model_name: "gpt-5"
    litellm_params:
      model: "github_copilot/gpt-5"
      extra_headers:
        "editor-version": "Neovim/0.11.0"
        "Copilot-Integration-Id": "vscode-chat"
